"""basemodel

Revision ID: 2e2901cb2668
Revises: b8c69d22d9d6
Create Date: 2025-02-10 14:15:26.233865

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e2901cb2668"
down_revision: str | None = "b8c69d22d9d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basemodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("basemodel")
    # ### end Alembic commands ###
