"""
This type stub file was generated by pyright.
"""

from . import exceptions
from ._version import __version__
from .connection import Connection
from .connection import connect
from .exceptions import *
from .pool import Pool
from .pool import create_pool
from .protocol import Record
from .types import *

__all__: tuple[str, ...] = ...
__all__ += exceptions.__all__
