name: Update CodeArtifact Token
on:
  schedule:
    # CodeArtifact token expires in 12 hours, update token every 11 hours
    - cron: 0 */11 * * *
  # run manually if needed
  workflow_dispatch:
jobs:
  set-codeartifact-token:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_WRITE_SECRETS_TOKEN }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # Read is required for actions/checkout and write to create a tag
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::354918389256:role/software-publishers"
          aws-region: "eu-west-1"
      - name: set codeartifact authorization token
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain-owner 354918389256 --domain repositories --query 'authorizationToken' --output text)
          gh secret set CODEARTIFACT_TOKEN --app dependabot --body "$CODEARTIFACT_AUTH_TOKEN"
          gh secret set CODEARTIFACT_TOKEN --body "$CODEARTIFACT_AUTH_TOKEN"
